# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=1.21.11
	yarn_mappings=1.21.11+build.4
	loader_version=0.18.4
	loom_version=1.14-SNAPSHOT

# Mod Properties
	mod_version = 1.6
	maven_group = io.github.inboundbark
	archives_base_name = viewbobbingmod
